<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    @if(isset($isPdf) && $isPdf)
        <link rel="stylesheet" href="{{ public_path('css/pdf/inventory-report.css') }}">
    @else
        <link rel="stylesheet" href="{{ asset('css/pdf/inventory-report.css') }}">
    @endif
</head>
<body>
    <div class="header">
        <h1>Inventory Report</h1>
        <p>Generated: {{ $generated_at }}</p>
        <p>Generated By: {{ $generated_by }}</p>
    </div>

    <div class="summary-boxes">
        <div class="summary-box">
            <div class="summary-label">Total Inventory Value</div>
            <div class="summary-value">PHP {{ number_format($summary['total_value'], 2) }}</div>
        </div>
        <div class="summary-box">
            <div class="summary-label">Total Inventory Items</div>
            <div class="summary-value">{{ $summary['total_items'] }}</div>
        </div>
        <div class="summary-box">
            <div class="summary-label">Low Stock Items</div>
            <div class="summary-value">{{ $summary['low_stock_count'] }}</div>
        </div>
        <div class="summary-box">
            <div class="summary-label">Stock Turnover Rate</div>
            <div class="summary-value">{{ $summary['turnover_rate'] }}%</div>
        </div>
    </div>

    <div class="section-title">Inventory Items</div>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>SKU</th>
                <th>Category</th>
                <th class="text-center">On Hand</th>
                <th class="text-center">Reorder Level</th>
                <th class="text-right">Avg Cost</th>
                <th>Last Purchase</th>
                <th class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($items as $item)
            @php
                $categoryValue = is_object($item->category) ? $item->category->value : $item->category;
                $categoryLabel = is_object($item->category) ? $item->category->label() : ucfirst(str_replace('_', ' ', $item->category));
            @endphp
            <tr>
                <td><strong>{{ $item->name }}</strong></td>
                <td>{{ $item->sku }}</td>
                <td>{{ $categoryLabel }}</td>
                <td class="text-center{{ $item->isLowStock() ? ' text-warning' : '' }}">
                    {{ $item->quantity_on_hand }} {{ $item->unit_of_measure }}
                </td>
                <td class="text-center">{{ $item->reorder_level }}</td>
                <td class="text-right">PHP {{ number_format($item->average_cost, 2) }}</td>
                <td>
                    @if($item->last_purchase_date)
                        {{ $item->last_purchase_date->format('M d, Y') }}
                    @else
                        <span class="text-muted">Never</span>
                    @endif
                </td>
                <td class="text-center{{ $item->isLowStock() ? ' text-warning' : '' }}">
                    @if($item->isLowStock())
                        Low Stock
                    @else
                        Normal
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="8" class="text-center text-muted">No inventory items found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="page-break"></div>

    <div class="section-title">Purchase History (Last 30 Days)</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Item</th>
                <th>SKU</th>
                <th class="text-center">Quantity</th>
                <th class="text-right">Unit Cost</th>
                <th class="text-right">Total Cost</th>
                <th>Vendor</th>
            </tr>
        </thead>
        <tbody>
            @forelse($purchase_history as $purchase)
            <tr>
                <td>{{ \Carbon\Carbon::parse($purchase->purchaseEntry->purchase_date)->format('M d, Y') }}</td>
                <td>{{ $purchase->inventoryItem->name ?? 'N/A' }}</td>
                <td>{{ $purchase->sku }}</td>
                <td class="text-center">{{ $purchase->quantity }}</td>
                <td class="text-right">PHP {{ number_format($purchase->unit_cost, 2) }}</td>
                <td class="text-right">PHP {{ number_format($purchase->total_cost, 2) }}</td>
                <td>{{ $purchase->purchaseEntry->vendor_name ?? 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center text-muted">No purchase history in the last 30 days</td>
            </tr>
            @endforelse
            @if($purchase_history->count() > 0)
            <tr style="background: #f3f4f6; font-weight: bold;">
                <td colspan="5">Total Purchases</td>
                <td class="text-right">PHP {{ number_format($purchase_history->sum('total_cost'), 2) }}</td>
                <td></td>
            </tr>
            @endif
        </tbody>
    </table>

    <div class="section-title">Stock Movements (Last 30 Days)</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Item</th>
                <th>SKU</th>
                <th class="text-center">Type</th>
                <th class="text-center">Quantity</th>
                <th>Reason</th>
                <th>Performed By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stock_movements as $movement)
            <tr>
                <td>{{ $movement->created_at->format('M d, Y g:i A') }}</td>
                <td>{{ $movement->inventoryItem->name ?? 'N/A' }}</td>
                <td>{{ $movement->sku }}</td>
                <td class="text-center">
                    @if($movement->movement_type === 'in')
                        <span style="color: #16a34a; font-weight: 600;">IN</span>
                    @else
                        <span style="color: #dc2626; font-weight: 600;">OUT</span>
                    @endif
                </td>
                <td class="text-center">{{ $movement->quantity }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $movement->reason ?? 'N/A')) }}</td>
                <td>{{ $movement->performer->name ?? 'System' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center text-muted">No stock movements in the last 30 days</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>JBRBS Booking Management System - Inventory Report</p>
        <p>This is a computer-generated document. No signature required.</p>
    </div>
</body>
</html>
